// NutriScan Food Library — Indian dishes, vegetables, fruits, junk food, healthy foods
// All values per 100g standard serving unless serving_size states otherwise

const EX_WALK = (cal) => ({ name: "Walking", duration: `${Math.round(cal / 4)} min`, intensity: "low", calories_burned: cal, description: "Brisk walk" });
const EX_RUN = (cal) => ({ name: "Running", duration: `${Math.round(cal / 10)} min`, intensity: "high", calories_burned: cal, description: "Steady run" });
const EX_CYCLE = (cal) => ({ name: "Cycling", duration: `${Math.round(cal / 8)} min`, intensity: "moderate", calories_burned: cal, description: "Cycling session" });
const EX_YOGA = (cal) => ({ name: "Yoga", duration: `${Math.round(cal / 3)} min`, intensity: "low", calories_burned: cal, description: "Light yoga" });
const EX_SWIM = (cal) => ({ name: "Swimming", duration: `${Math.round(cal / 9)} min`, intensity: "moderate", calories_burned: cal, description: "Freestyle swimming" });

export const INDIAN_FOOD_LIBRARY = [
  // ─── INDIAN DISHES ───
  { food_name: "Biryani", food_category: "moderate", calories: 150, protein: 8, carbs: 20, fats: 4, fiber: 1, sugar: 1, serving_size: "1 cup (200g)", health_warning: "High in refined carbs and fat.", healthier_alternatives: "Try vegetable biryani with brown rice.", exercises: [EX_WALK(150), EX_CYCLE(150)], vitamins: [{ name: "Vitamin B12", amount: "0.5mcg" }, { name: "Iron", amount: "2mg" }] },
  { food_name: "Dal Tadka", food_category: "healthy", calories: 116, protein: 7, carbs: 18, fats: 3, fiber: 5, sugar: 2, serving_size: "1 bowl (200g)", health_warning: "", healthier_alternatives: "", exercises: [EX_YOGA(116)], vitamins: [{ name: "Iron", amount: "3mg" }, { name: "Folate", amount: "180mcg" }] },
  { food_name: "Paneer Butter Masala", food_category: "moderate", calories: 180, protein: 10, carbs: 8, fats: 13, fiber: 1, sugar: 4, serving_size: "1 bowl (200g)", health_warning: "High in saturated fat.", healthier_alternatives: "Paneer in tomato-based gravy without cream.", exercises: [EX_RUN(180), EX_SWIM(180)], vitamins: [{ name: "Calcium", amount: "200mg" }] },
  { food_name: "Roti / Chapati", food_category: "healthy", calories: 104, protein: 3, carbs: 19, fats: 2, fiber: 2, sugar: 0, serving_size: "1 roti (40g)", health_warning: "", healthier_alternatives: "", exercises: [EX_WALK(104)], vitamins: [{ name: "Iron", amount: "1.5mg" }] },
  { food_name: "Samosa", food_category: "unhealthy", calories: 262, protein: 4, carbs: 30, fats: 14, fiber: 2, sugar: 2, serving_size: "2 pieces (100g)", health_warning: "Deep fried and high in calories.", healthier_alternatives: "Baked samosa or steamed momos.", exercises: [EX_RUN(262), EX_CYCLE(262)], vitamins: [] },
  { food_name: "Idli", food_category: "healthy", calories: 58, protein: 2, carbs: 11, fats: 0.5, fiber: 1, sugar: 0, serving_size: "2 idlis (100g)", health_warning: "", healthier_alternatives: "", exercises: [EX_YOGA(58)], vitamins: [{ name: "Iron", amount: "1mg" }] },
  { food_name: "Dosa", food_category: "healthy", calories: 168, protein: 4, carbs: 29, fats: 4, fiber: 1, sugar: 1, serving_size: "1 dosa (100g)", health_warning: "", healthier_alternatives: "", exercises: [EX_WALK(168)], vitamins: [{ name: "Iron", amount: "1.5mg" }] },
  { food_name: "Chole Bhature", food_category: "unhealthy", calories: 296, protein: 10, carbs: 45, fats: 10, fiber: 5, sugar: 3, serving_size: "1 plate (200g)", health_warning: "Very high calorie. Deep-fried bread.", healthier_alternatives: "Chole with tandoori roti.", exercises: [EX_RUN(296)], vitamins: [{ name: "Iron", amount: "4mg" }] },
  { food_name: "Rajma Chawal", food_category: "healthy", calories: 130, protein: 7, carbs: 24, fats: 1, fiber: 6, sugar: 2, serving_size: "1 bowl (250g)", health_warning: "", healthier_alternatives: "", exercises: [EX_WALK(130)], vitamins: [{ name: "Iron", amount: "3mg" }] },
  { food_name: "Aloo Paratha", food_category: "moderate", calories: 210, protein: 5, carbs: 33, fats: 7, fiber: 2, sugar: 1, serving_size: "1 paratha (100g)", health_warning: "Made with ghee. Have in moderation.", healthier_alternatives: "Whole wheat paratha with less ghee.", exercises: [EX_CYCLE(210), EX_WALK(210)], vitamins: [{ name: "Vitamin C", amount: "10mg" }] },
  { food_name: "Palak Paneer", food_category: "healthy", calories: 140, protein: 9, carbs: 6, fats: 9, fiber: 3, sugar: 2, serving_size: "1 bowl (200g)", health_warning: "", healthier_alternatives: "", exercises: [EX_YOGA(140)], vitamins: [{ name: "Iron", amount: "5mg" }, { name: "Vitamin K", amount: "400mcg" }] },
  { food_name: "Butter Chicken", food_category: "moderate", calories: 170, protein: 15, carbs: 7, fats: 10, fiber: 1, sugar: 4, serving_size: "1 bowl (200g)", health_warning: "High in saturated fat due to cream.", healthier_alternatives: "Tandoori chicken without cream sauce.", exercises: [EX_RUN(170)], vitamins: [{ name: "Vitamin A", amount: "200mcg" }] },
  { food_name: "Poha", food_category: "healthy", calories: 110, protein: 3, carbs: 23, fats: 1, fiber: 1, sugar: 1, serving_size: "1 bowl (150g)", health_warning: "", healthier_alternatives: "", exercises: [EX_WALK(110)], vitamins: [{ name: "Iron", amount: "2mg" }] },
  { food_name: "Upma", food_category: "healthy", calories: 100, protein: 3, carbs: 18, fats: 3, fiber: 2, sugar: 1, serving_size: "1 bowl (150g)", health_warning: "", healthier_alternatives: "", exercises: [EX_YOGA(100)], vitamins: [{ name: "Iron", amount: "1.5mg" }] },
  { food_name: "Vada Pav", food_category: "unhealthy", calories: 290, protein: 7, carbs: 45, fats: 10, fiber: 2, sugar: 3, serving_size: "1 piece (150g)", health_warning: "Deep-fried vada with refined bread.", healthier_alternatives: "Tikki made from oats or sweet potato.", exercises: [EX_RUN(290)], vitamins: [] },
  { food_name: "Pani Puri", food_category: "moderate", calories: 180, protein: 3, carbs: 28, fats: 6, fiber: 2, sugar: 2, serving_size: "6 pieces (100g)", health_warning: "Deep-fried shells.", healthier_alternatives: "Make at home with baked puris.", exercises: [EX_WALK(180)], vitamins: [] },
  { food_name: "Masala Chai", food_category: "healthy", calories: 60, protein: 2, carbs: 8, fats: 2, fiber: 0, sugar: 6, serving_size: "1 cup (200ml)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Antioxidants", amount: "High" }] },
  { food_name: "Khichdi", food_category: "healthy", calories: 100, protein: 4, carbs: 18, fats: 2, fiber: 2, sugar: 1, serving_size: "1 bowl (200g)", health_warning: "", healthier_alternatives: "", exercises: [EX_WALK(100)], vitamins: [{ name: "Iron", amount: "2mg" }] },
  { food_name: "Gulab Jamun", food_category: "unhealthy", calories: 380, protein: 5, carbs: 60, fats: 14, fiber: 0, sugar: 45, serving_size: "2 pieces (100g)", health_warning: "Extremely high in sugar and fat.", healthier_alternatives: "Dates or fruit-based sweets.", exercises: [EX_RUN(380)], vitamins: [] },
  { food_name: "Raita", food_category: "healthy", calories: 60, protein: 3, carbs: 5, fats: 3, fiber: 0.5, sugar: 4, serving_size: "1 bowl (150g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Calcium", amount: "150mg" }] },
  { food_name: "Pav Bhaji", food_category: "moderate", calories: 250, protein: 6, carbs: 38, fats: 9, fiber: 4, sugar: 5, serving_size: "1 plate (250g)", health_warning: "High in butter.", healthier_alternatives: "Whole wheat pav with less butter.", exercises: [EX_CYCLE(250)], vitamins: [{ name: "Vitamin C", amount: "20mg" }] },
  { food_name: "Tandoori Chicken", food_category: "healthy", calories: 165, protein: 25, carbs: 3, fats: 6, fiber: 0, sugar: 1, serving_size: "2 pieces (150g)", health_warning: "", healthier_alternatives: "", exercises: [EX_WALK(165)], vitamins: [{ name: "Vitamin B12", amount: "2mcg" }] },
  { food_name: "Fish Curry", food_category: "healthy", calories: 130, protein: 18, carbs: 5, fats: 5, fiber: 1, sugar: 2, serving_size: "1 bowl (200g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Omega-3", amount: "1g" }] },
  { food_name: "Egg Bhurji", food_category: "healthy", calories: 150, protein: 12, carbs: 3, fats: 10, fiber: 0.5, sugar: 1, serving_size: "1 serving (150g)", health_warning: "", healthier_alternatives: "", exercises: [EX_YOGA(150)], vitamins: [{ name: "Vitamin D", amount: "3mcg" }] },
  { food_name: "Pulao", food_category: "healthy", calories: 120, protein: 3, carbs: 22, fats: 3, fiber: 1, sugar: 1, serving_size: "1 cup (180g)", health_warning: "", healthier_alternatives: "", exercises: [EX_WALK(120)], vitamins: [{ name: "Iron", amount: "1mg" }] },
  { food_name: "Matar Paneer", food_category: "healthy", calories: 155, protein: 9, carbs: 10, fats: 9, fiber: 3, sugar: 3, serving_size: "1 bowl (200g)", health_warning: "", healthier_alternatives: "", exercises: [EX_WALK(155)], vitamins: [{ name: "Calcium", amount: "180mg" }] },
  { food_name: "Dum Aloo", food_category: "moderate", calories: 175, protein: 4, carbs: 24, fats: 8, fiber: 3, sugar: 4, serving_size: "1 bowl (200g)", health_warning: "Moderate oil content.", healthier_alternatives: "Bake potatoes instead of frying.", exercises: [EX_CYCLE(175)], vitamins: [{ name: "Vitamin C", amount: "12mg" }] },
  { food_name: "Lassi", food_category: "healthy", calories: 100, protein: 4, carbs: 15, fats: 3, fiber: 0, sugar: 14, serving_size: "1 glass (300ml)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Calcium", amount: "180mg" }] },
  { food_name: "Jalebi", food_category: "unhealthy", calories: 450, protein: 2, carbs: 70, fats: 18, fiber: 0, sugar: 55, serving_size: "4 pieces (100g)", health_warning: "Extremely high sugar. Diabetics should avoid.", healthier_alternatives: "Fresh fruit chaat.", exercises: [EX_RUN(450)], vitamins: [] },
  { food_name: "Uttapam", food_category: "healthy", calories: 120, protein: 4, carbs: 20, fats: 3, fiber: 2, sugar: 2, serving_size: "1 piece (100g)", health_warning: "", healthier_alternatives: "", exercises: [EX_WALK(120)], vitamins: [{ name: "Iron", amount: "1mg" }] },
  { food_name: "Sabudana Khichdi", food_category: "moderate", calories: 200, protein: 2, carbs: 40, fats: 6, fiber: 0.5, sugar: 2, serving_size: "1 bowl (150g)", health_warning: "Low protein, high starch.", healthier_alternatives: "Add peanuts and curd.", exercises: [EX_YOGA(200)], vitamins: [] },
  { food_name: "Baingan Bharta", food_category: "healthy", calories: 80, protein: 3, carbs: 9, fats: 4, fiber: 4, sugar: 4, serving_size: "1 bowl (150g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin B6", amount: "0.3mg" }] },
  { food_name: "Chicken Tikka Masala", food_category: "moderate", calories: 180, protein: 18, carbs: 9, fats: 9, fiber: 1, sugar: 5, serving_size: "1 bowl (200g)", health_warning: "Restaurant versions very high in cream.", healthier_alternatives: "Cook at home with low-fat yogurt.", exercises: [EX_RUN(180)], vitamins: [{ name: "Vitamin A", amount: "180mcg" }] },
  { food_name: "Momos", food_category: "moderate", calories: 180, protein: 9, carbs: 26, fats: 5, fiber: 1, sugar: 1, serving_size: "6 pieces (150g)", health_warning: "Steamed better than fried.", healthier_alternatives: "Choose steamed momos.", exercises: [EX_WALK(180)], vitamins: [] },
  { food_name: "Halwa", food_category: "unhealthy", calories: 360, protein: 4, carbs: 52, fats: 16, fiber: 1, sugar: 38, serving_size: "1 cup (150g)", health_warning: "High in sugar and ghee.", healthier_alternatives: "Carrot halwa with less sugar.", exercises: [EX_CYCLE(360)], vitamins: [] },
  { food_name: "Dhokla", food_category: "healthy", calories: 130, protein: 6, carbs: 20, fats: 3, fiber: 1, sugar: 3, serving_size: "4 pieces (100g)", health_warning: "", healthier_alternatives: "", exercises: [EX_WALK(130)], vitamins: [{ name: "Iron", amount: "1.5mg" }] },
  { food_name: "Chana Masala", food_category: "healthy", calories: 120, protein: 7, carbs: 18, fats: 3, fiber: 6, sugar: 3, serving_size: "1 bowl (200g)", health_warning: "", healthier_alternatives: "", exercises: [EX_YOGA(120)], vitamins: [{ name: "Iron", amount: "4mg" }] },
  { food_name: "Dahi Vada", food_category: "moderate", calories: 185, protein: 7, carbs: 25, fats: 6, fiber: 2, sugar: 8, serving_size: "2 pieces (150g)", health_warning: "Deep-fried lentil fritters.", healthier_alternatives: "Baked vada or raita.", exercises: [EX_WALK(185)], vitamins: [{ name: "Calcium", amount: "150mg" }] },
  { food_name: "Sarson Da Saag", food_category: "healthy", calories: 90, protein: 5, carbs: 10, fats: 4, fiber: 5, sugar: 2, serving_size: "1 bowl (150g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin K", amount: "500mcg" }, { name: "Iron", amount: "4mg" }] },
  { food_name: "Makki Di Roti", food_category: "healthy", calories: 150, protein: 3, carbs: 30, fats: 2, fiber: 3, sugar: 1, serving_size: "1 roti (80g)", health_warning: "", healthier_alternatives: "", exercises: [EX_WALK(150)], vitamins: [{ name: "Magnesium", amount: "30mg" }] },
  { food_name: "Kadhi Pakora", food_category: "moderate", calories: 165, protein: 5, carbs: 18, fats: 8, fiber: 2, sugar: 4, serving_size: "1 bowl (200g)", health_warning: "Pakoras are deep-fried.", healthier_alternatives: "Plain kadhi without pakoras.", exercises: [EX_YOGA(165)], vitamins: [{ name: "Calcium", amount: "120mg" }] },
  { food_name: "Lemon Rice", food_category: "healthy", calories: 130, protein: 2, carbs: 27, fats: 3, fiber: 1, sugar: 1, serving_size: "1 cup (150g)", health_warning: "", healthier_alternatives: "", exercises: [EX_WALK(130)], vitamins: [{ name: "Vitamin C", amount: "8mg" }] },
  { food_name: "Appam", food_category: "healthy", calories: 120, protein: 3, carbs: 24, fats: 1, fiber: 1, sugar: 2, serving_size: "2 pieces (100g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Iron", amount: "1mg" }] },
  { food_name: "Avial", food_category: "healthy", calories: 100, protein: 3, carbs: 12, fats: 5, fiber: 4, sugar: 3, serving_size: "1 bowl (150g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "20mg" }] },
  { food_name: "Kachori", food_category: "unhealthy", calories: 310, protein: 6, carbs: 35, fats: 16, fiber: 3, sugar: 2, serving_size: "2 pieces (100g)", health_warning: "Heavily deep-fried.", healthier_alternatives: "Baked whole-wheat stuffed bread.", exercises: [EX_RUN(310)], vitamins: [] },
  { food_name: "Besan Chilla", food_category: "healthy", calories: 120, protein: 6, carbs: 15, fats: 4, fiber: 3, sugar: 2, serving_size: "2 pieces (100g)", health_warning: "", healthier_alternatives: "", exercises: [EX_WALK(120)], vitamins: [{ name: "Iron", amount: "2mg" }] },
  { food_name: "Fruit Chaat", food_category: "healthy", calories: 70, protein: 1, carbs: 17, fats: 0.5, fiber: 3, sugar: 14, serving_size: "1 bowl (150g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "40mg" }] },
  { food_name: "Mishti Doi", food_category: "moderate", calories: 150, protein: 5, carbs: 25, fats: 4, fiber: 0, sugar: 22, serving_size: "1 cup (150g)", health_warning: "High sugar. Limit if diabetic.", healthier_alternatives: "Plain dahi with honey.", exercises: [EX_WALK(150)], vitamins: [{ name: "Calcium", amount: "160mg" }] },
  { food_name: "Kofte", food_category: "moderate", calories: 200, protein: 10, carbs: 12, fats: 12, fiber: 2, sugar: 3, serving_size: "4 pieces (150g)", health_warning: "Deep-fried koftes high in fat.", healthier_alternatives: "Bake or air-fry the koftes.", exercises: [EX_CYCLE(200)], vitamins: [] },
  { food_name: "Curd Rice", food_category: "healthy", calories: 100, protein: 4, carbs: 18, fats: 2, fiber: 0.5, sugar: 4, serving_size: "1 bowl (200g)", health_warning: "", healthier_alternatives: "", exercises: [EX_YOGA(100)], vitamins: [{ name: "Calcium", amount: "100mg" }] },
  { food_name: "Mutton Curry", food_category: "moderate", calories: 190, protein: 20, carbs: 5, fats: 11, fiber: 1, sugar: 2, serving_size: "1 bowl (200g)", health_warning: "High in saturated fat. Limit red meat.", healthier_alternatives: "Chicken or fish curry.", exercises: [EX_RUN(190)], vitamins: [{ name: "Iron", amount: "3.5mg" }, { name: "Vitamin B12", amount: "2.5mcg" }] },

  // ─── VEGETABLES ───
  { food_name: "Spinach", food_category: "healthy", calories: 23, protein: 2.9, carbs: 3.6, fats: 0.4, fiber: 2.2, sugar: 0.4, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin K", amount: "483mcg" }, { name: "Iron", amount: "2.7mg" }, { name: "Vitamin A", amount: "469mcg" }] },
  { food_name: "Broccoli", food_category: "healthy", calories: 34, protein: 2.8, carbs: 7, fats: 0.4, fiber: 2.6, sugar: 1.7, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "89mg" }, { name: "Vitamin K", amount: "102mcg" }] },
  { food_name: "Carrot", food_category: "healthy", calories: 41, protein: 0.9, carbs: 10, fats: 0.2, fiber: 2.8, sugar: 4.7, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin A", amount: "835mcg" }, { name: "Vitamin K", amount: "13mcg" }] },
  { food_name: "Tomato", food_category: "healthy", calories: 18, protein: 0.9, carbs: 3.9, fats: 0.2, fiber: 1.2, sugar: 2.6, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "14mg" }, { name: "Lycopene", amount: "High" }] },
  { food_name: "Cucumber", food_category: "healthy", calories: 15, protein: 0.7, carbs: 3.6, fats: 0.1, fiber: 0.5, sugar: 1.7, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin K", amount: "16mcg" }] },
  { food_name: "Onion", food_category: "healthy", calories: 40, protein: 1.1, carbs: 9.3, fats: 0.1, fiber: 1.7, sugar: 4.2, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "7mg" }] },
  { food_name: "Potato", food_category: "moderate", calories: 77, protein: 2, carbs: 17, fats: 0.1, fiber: 2.2, sugar: 0.8, serving_size: "100g", health_warning: "High glycemic. Avoid frying.", healthier_alternatives: "Sweet potato.", exercises: [EX_WALK(77)], vitamins: [{ name: "Vitamin C", amount: "20mg" }, { name: "Potassium", amount: "421mg" }] },
  { food_name: "Sweet Potato", food_category: "healthy", calories: 86, protein: 1.6, carbs: 20, fats: 0.1, fiber: 3, sugar: 4.2, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin A", amount: "961mcg" }, { name: "Vitamin C", amount: "2.4mg" }] },
  { food_name: "Cauliflower", food_category: "healthy", calories: 25, protein: 1.9, carbs: 5, fats: 0.3, fiber: 2, sugar: 1.9, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "48mg" }, { name: "Vitamin K", amount: "15.5mcg" }] },
  { food_name: "Cabbage", food_category: "healthy", calories: 25, protein: 1.3, carbs: 5.8, fats: 0.1, fiber: 2.5, sugar: 3.2, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "36mg" }, { name: "Vitamin K", amount: "76mcg" }] },
  { food_name: "Capsicum (Bell Pepper)", food_category: "healthy", calories: 20, protein: 0.9, carbs: 4.6, fats: 0.2, fiber: 1.7, sugar: 2.4, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "128mg" }, { name: "Vitamin A", amount: "157mcg" }] },
  { food_name: "Bitter Gourd (Karela)", food_category: "healthy", calories: 17, protein: 1, carbs: 3.7, fats: 0.2, fiber: 2.8, sugar: 1.7, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "84mg" }, { name: "Iron", amount: "0.4mg" }] },
  { food_name: "Bottle Gourd (Lauki)", food_category: "healthy", calories: 15, protein: 0.6, carbs: 3.4, fats: 0.1, fiber: 0.5, sugar: 1.5, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "10mg" }] },
  { food_name: "Ridge Gourd (Turai)", food_category: "healthy", calories: 18, protein: 1.2, carbs: 3.6, fats: 0.1, fiber: 0.5, sugar: 1.2, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "12mg" }] },
  { food_name: "Drumstick (Moringa)", food_category: "healthy", calories: 37, protein: 2, carbs: 8.5, fats: 0.1, fiber: 3.2, sugar: 1.8, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "141mg" }, { name: "Iron", amount: "0.4mg" }] },
  { food_name: "Pumpkin", food_category: "healthy", calories: 26, protein: 1, carbs: 6.5, fats: 0.1, fiber: 0.5, sugar: 2.8, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin A", amount: "426mcg" }] },
  { food_name: "Peas (Matar)", food_category: "healthy", calories: 81, protein: 5.4, carbs: 14, fats: 0.4, fiber: 5.1, sugar: 5.7, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "40mg" }, { name: "Vitamin K", amount: "24mcg" }] },
  { food_name: "Beans (French)", food_category: "healthy", calories: 31, protein: 1.8, carbs: 7, fats: 0.2, fiber: 3.4, sugar: 1.4, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "12mg" }, { name: "Vitamin K", amount: "14.4mcg" }] },
  { food_name: "Lady Finger (Bhindi/Okra)", food_category: "healthy", calories: 33, protein: 1.9, carbs: 7.5, fats: 0.2, fiber: 3.2, sugar: 1.5, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "23mg" }, { name: "Vitamin K", amount: "31.3mcg" }] },
  { food_name: "Lotus Root (Kamal Kakdi)", food_category: "healthy", calories: 74, protein: 2.6, carbs: 17, fats: 0.1, fiber: 4.9, sugar: 0.3, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "44mg" }] },
  { food_name: "Colocasia (Arbi/Taro)", food_category: "moderate", calories: 112, protein: 1.5, carbs: 26, fats: 0.2, fiber: 4.1, sugar: 0.4, serving_size: "100g", health_warning: "High carb. Diabetics should limit.", healthier_alternatives: "", exercises: [EX_WALK(112)], vitamins: [{ name: "Vitamin E", amount: "2.4mg" }] },
  { food_name: "Fenugreek Leaves (Methi)", food_category: "healthy", calories: 49, protein: 4.4, carbs: 6, fats: 0.9, fiber: 2.7, sugar: 1, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Iron", amount: "2.7mg" }, { name: "Vitamin K", amount: "36mcg" }] },
  { food_name: "Radish (Mooli)", food_category: "healthy", calories: 16, protein: 0.7, carbs: 3.4, fats: 0.1, fiber: 1.6, sugar: 2, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "15mg" }] },
  { food_name: "Beetroot", food_category: "healthy", calories: 43, protein: 1.6, carbs: 10, fats: 0.2, fiber: 2.8, sugar: 7, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Folate", amount: "109mcg" }, { name: "Iron", amount: "0.8mg" }] },
  { food_name: "Corn / Maize", food_category: "moderate", calories: 96, protein: 3.4, carbs: 21, fats: 1.5, fiber: 2.4, sugar: 3.2, serving_size: "100g", health_warning: "Moderate glycemic index.", healthier_alternatives: "", exercises: [EX_WALK(96)], vitamins: [{ name: "Vitamin C", amount: "7mg" }, { name: "Thiamine", amount: "0.2mg" }] },
  { food_name: "Zucchini", food_category: "healthy", calories: 17, protein: 1.2, carbs: 3.1, fats: 0.3, fiber: 1, sugar: 2.5, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "17mg" }] },
  { food_name: "Mushroom", food_category: "healthy", calories: 22, protein: 3.1, carbs: 3.3, fats: 0.3, fiber: 1, sugar: 2, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin D", amount: "0.2mcg" }, { name: "Selenium", amount: "9.3mcg" }] },
  { food_name: "Garlic", food_category: "healthy", calories: 149, protein: 6.4, carbs: 33, fats: 0.5, fiber: 2.1, sugar: 1, serving_size: "10g (3 cloves)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "31mg" }, { name: "Allicin", amount: "High" }] },
  { food_name: "Ginger", food_category: "healthy", calories: 80, protein: 1.8, carbs: 18, fats: 0.8, fiber: 2, sugar: 1.7, serving_size: "10g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Magnesium", amount: "43mg" }] },
  { food_name: "Coriander Leaves (Dhaniya)", food_category: "healthy", calories: 23, protein: 2.1, carbs: 3.7, fats: 0.5, fiber: 2.8, sugar: 0.9, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin K", amount: "310mcg" }, { name: "Vitamin A", amount: "337mcg" }] },
  { food_name: "Curry Leaves", food_category: "healthy", calories: 108, protein: 6.1, carbs: 18.7, fats: 1, fiber: 6.4, sugar: 3, serving_size: "10g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Iron", amount: "7mg" }, { name: "Calcium", amount: "830mg" }] },
  { food_name: "Ash Gourd (Petha)", food_category: "healthy", calories: 13, protein: 0.4, carbs: 3, fats: 0.2, fiber: 0.6, sugar: 1.6, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "13mg" }] },
  { food_name: "Cluster Beans (Gavar)", food_category: "healthy", calories: 16, protein: 3.2, carbs: 0, fats: 0.4, fiber: 1.7, sugar: 0, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Iron", amount: "1.4mg" }] },
  { food_name: "Raw Banana (Kacha Kela)", food_category: "moderate", calories: 89, protein: 1.3, carbs: 22, fats: 0.1, fiber: 2.6, sugar: 5, serving_size: "100g", health_warning: "High in starch.", healthier_alternatives: "", exercises: [EX_WALK(89)], vitamins: [{ name: "Vitamin B6", amount: "0.4mg" }] },
  { food_name: "Brinjal (Baingan/Eggplant)", food_category: "healthy", calories: 25, protein: 1, carbs: 6, fats: 0.2, fiber: 3, sugar: 3.5, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin B1", amount: "0.08mg" }] },
  { food_name: "Turnip (Shalgam)", food_category: "healthy", calories: 28, protein: 0.9, carbs: 6.4, fats: 0.1, fiber: 1.8, sugar: 3.8, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "21mg" }] },

  // ─── FRUITS ───
  { food_name: "Mango", food_category: "healthy", calories: 60, protein: 0.8, carbs: 15, fats: 0.4, fiber: 1.6, sugar: 13.7, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "36mg" }, { name: "Vitamin A", amount: "54mcg" }] },
  { food_name: "Banana", food_category: "healthy", calories: 89, protein: 1.1, carbs: 23, fats: 0.3, fiber: 2.6, sugar: 12, serving_size: "1 medium (100g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin B6", amount: "0.4mg" }, { name: "Potassium", amount: "358mg" }] },
  { food_name: "Apple", food_category: "healthy", calories: 52, protein: 0.3, carbs: 14, fats: 0.2, fiber: 2.4, sugar: 10, serving_size: "1 medium (150g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "5mg" }, { name: "Quercetin", amount: "High" }] },
  { food_name: "Orange", food_category: "healthy", calories: 47, protein: 0.9, carbs: 12, fats: 0.1, fiber: 2.4, sugar: 9.4, serving_size: "1 medium (130g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "53mg" }, { name: "Folate", amount: "30mcg" }] },
  { food_name: "Papaya", food_category: "healthy", calories: 43, protein: 0.5, carbs: 11, fats: 0.3, fiber: 1.7, sugar: 7.8, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "62mg" }, { name: "Vitamin A", amount: "47mcg" }] },
  { food_name: "Guava", food_category: "healthy", calories: 68, protein: 2.6, carbs: 14, fats: 1, fiber: 5.4, sugar: 8.9, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "228mg" }, { name: "Potassium", amount: "417mg" }] },
  { food_name: "Watermelon", food_category: "healthy", calories: 30, protein: 0.6, carbs: 7.6, fats: 0.2, fiber: 0.4, sugar: 6.2, serving_size: "1 cup (154g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "12mg" }, { name: "Lycopene", amount: "High" }] },
  { food_name: "Grapes", food_category: "healthy", calories: 69, protein: 0.7, carbs: 18, fats: 0.2, fiber: 0.9, sugar: 15, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin K", amount: "14.6mcg" }, { name: "Resveratrol", amount: "High" }] },
  { food_name: "Pomegranate", food_category: "healthy", calories: 83, protein: 1.7, carbs: 19, fats: 1.2, fiber: 4, sugar: 13.7, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "10mg" }, { name: "Vitamin K", amount: "16.4mcg" }] },
  { food_name: "Pineapple", food_category: "healthy", calories: 50, protein: 0.5, carbs: 13, fats: 0.1, fiber: 1.4, sugar: 10, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "48mg" }, { name: "Manganese", amount: "0.9mg" }] },
  { food_name: "Strawberry", food_category: "healthy", calories: 32, protein: 0.7, carbs: 7.7, fats: 0.3, fiber: 2, sugar: 4.9, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "59mg" }, { name: "Folate", amount: "24mcg" }] },
  { food_name: "Kiwi", food_category: "healthy", calories: 61, protein: 1.1, carbs: 15, fats: 0.5, fiber: 3, sugar: 9, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "93mg" }, { name: "Vitamin K", amount: "40.3mcg" }] },
  { food_name: "Lychee", food_category: "healthy", calories: 66, protein: 0.8, carbs: 17, fats: 0.4, fiber: 1.3, sugar: 15, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "72mg" }] },
  { food_name: "Chiku (Sapota)", food_category: "moderate", calories: 83, protein: 0.4, carbs: 20, fats: 1.1, fiber: 5.3, sugar: 14, serving_size: "100g", health_warning: "High in natural sugars.", healthier_alternatives: "", exercises: [EX_WALK(83)], vitamins: [{ name: "Vitamin C", amount: "14mg" }] },
  { food_name: "Coconut", food_category: "moderate", calories: 354, protein: 3.3, carbs: 15, fats: 33, fiber: 9, sugar: 6.2, serving_size: "30g (1 piece)", health_warning: "High in saturated fat.", healthier_alternatives: "", exercises: [EX_CYCLE(354)], vitamins: [{ name: "Manganese", amount: "1.5mg" }] },
  { food_name: "Jamun (Indian Blackberry)", food_category: "healthy", calories: 60, protein: 0.7, carbs: 14, fats: 0.3, fiber: 0.9, sugar: 13, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "18mg" }, { name: "Iron", amount: "0.2mg" }] },
  { food_name: "Amla (Indian Gooseberry)", food_category: "healthy", calories: 44, protein: 0.9, carbs: 10, fats: 0.6, fiber: 4.3, sugar: 6, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "600mg" }, { name: "Iron", amount: "1.2mg" }] },
  { food_name: "Pear", food_category: "healthy", calories: 57, protein: 0.4, carbs: 15, fats: 0.1, fiber: 3.1, sugar: 10, serving_size: "1 medium (170g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "4mg" }, { name: "Vitamin K", amount: "4.4mcg" }] },
  { food_name: "Plum", food_category: "healthy", calories: 46, protein: 0.7, carbs: 11, fats: 0.3, fiber: 1.4, sugar: 9.9, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "9.5mg" }, { name: "Vitamin A", amount: "17mcg" }] },
  { food_name: "Dates (Khajoor)", food_category: "moderate", calories: 277, protein: 1.8, carbs: 75, fats: 0.2, fiber: 6.7, sugar: 63, serving_size: "3-4 dates (30g)", health_warning: "Very high in sugar. Eat in small portions.", healthier_alternatives: "", exercises: [EX_CYCLE(277)], vitamins: [{ name: "Iron", amount: "0.9mg" }, { name: "Potassium", amount: "696mg" }] },

  // ─── JUNK FOOD ───
  { food_name: "Burger", food_category: "unhealthy", calories: 295, protein: 17, carbs: 24, fats: 14, fiber: 1, sugar: 7, serving_size: "1 burger (150g)", health_warning: "High in saturated fat, sodium, and refined carbs.", healthier_alternatives: "Whole wheat bun veggie burger.", exercises: [EX_RUN(295), EX_CYCLE(295)], vitamins: [] },
  { food_name: "Pizza", food_category: "unhealthy", calories: 266, protein: 11, carbs: 33, fats: 10, fiber: 2.3, sugar: 3.6, serving_size: "2 slices (200g)", health_warning: "High in saturated fat and refined flour.", healthier_alternatives: "Thin crust veggie pizza with less cheese.", exercises: [EX_RUN(266)], vitamins: [] },
  { food_name: "French Fries", food_category: "unhealthy", calories: 312, protein: 3.4, carbs: 41, fats: 15, fiber: 3.8, sugar: 0.3, serving_size: "1 medium serving (115g)", health_warning: "Deep fried, high in trans fat and sodium.", healthier_alternatives: "Baked potato wedges.", exercises: [EX_RUN(312)], vitamins: [{ name: "Vitamin C", amount: "10mg" }] },
  { food_name: "Potato Chips", food_category: "unhealthy", calories: 536, protein: 7, carbs: 53, fats: 35, fiber: 4.8, sugar: 0.4, serving_size: "1 small pack (50g)", health_warning: "Extremely high in fat, sodium, and acrylamide.", healthier_alternatives: "Roasted makhana or baked chips.", exercises: [EX_RUN(536)], vitamins: [] },
  { food_name: "Instant Noodles (Maggi)", food_category: "unhealthy", calories: 420, protein: 9, carbs: 58, fats: 17, fiber: 2, sugar: 2, serving_size: "1 pack (85g)", health_warning: "Very high in sodium and refined carbs. Low nutrition.", healthier_alternatives: "Whole wheat noodles with vegetables.", exercises: [EX_RUN(420)], vitamins: [] },
  { food_name: "Hot Dog", food_category: "unhealthy", calories: 290, protein: 12, carbs: 22, fats: 17, fiber: 0.9, sugar: 5, serving_size: "1 piece (130g)", health_warning: "Processed meat, high sodium, carcinogenic additives.", healthier_alternatives: "Grilled chicken sandwich.", exercises: [EX_RUN(290)], vitamins: [] },
  { food_name: "Fried Chicken (KFC-style)", food_category: "unhealthy", calories: 320, protein: 21, carbs: 15, fats: 21, fiber: 0.5, sugar: 0.5, serving_size: "1 piece (130g)", health_warning: "High in saturated fat from deep frying.", healthier_alternatives: "Air-fried or baked chicken.", exercises: [EX_RUN(320)], vitamins: [] },
  { food_name: "Chocolate Bar", food_category: "unhealthy", calories: 535, protein: 7.7, carbs: 60, fats: 30, fiber: 3.4, sugar: 52, serving_size: "1 bar (50g)", health_warning: "High in sugar and saturated fat.", healthier_alternatives: "Dark chocolate (70%+) in moderation.", exercises: [EX_RUN(535)], vitamins: [] },
  { food_name: "Ice Cream", food_category: "unhealthy", calories: 207, protein: 3.5, carbs: 24, fats: 11, fiber: 0.7, sugar: 21, serving_size: "1 scoop (100g)", health_warning: "High in sugar and saturated fat.", healthier_alternatives: "Frozen yogurt or banana ice cream.", exercises: [EX_CYCLE(207)], vitamins: [] },
  { food_name: "Soft Drink (Cola)", food_category: "unhealthy", calories: 40, protein: 0, carbs: 10.6, fats: 0, fiber: 0, sugar: 10.6, serving_size: "1 can (350ml)", health_warning: "Pure liquid sugar. Zero nutrition. Highly acidic.", healthier_alternatives: "Coconut water or nimbu pani.", exercises: [EX_WALK(140)], vitamins: [] },
  { food_name: "Doughnut", food_category: "unhealthy", calories: 452, protein: 5, carbs: 51, fats: 25, fiber: 1.7, sugar: 21, serving_size: "1 glazed (100g)", health_warning: "Deep fried and glazed with sugar. Empty calories.", healthier_alternatives: "Whole wheat baked muffin.", exercises: [EX_RUN(452)], vitamins: [] },
  { food_name: "Nachos with Cheese", food_category: "unhealthy", calories: 306, protein: 7, carbs: 37, fats: 15, fiber: 3.5, sugar: 1, serving_size: "1 serving (100g)", health_warning: "High in sodium and saturated fat.", healthier_alternatives: "Baked tortilla chips with salsa.", exercises: [EX_RUN(306)], vitamins: [] },
  { food_name: "Fried Spring Rolls", food_category: "unhealthy", calories: 260, protein: 5, carbs: 30, fats: 13, fiber: 2, sugar: 2, serving_size: "3 pieces (100g)", health_warning: "Deep fried, refined flour wrapper.", healthier_alternatives: "Steamed or baked spring rolls.", exercises: [EX_CYCLE(260)], vitamins: [] },
  { food_name: "Biscuits (Cream)", food_category: "unhealthy", calories: 480, protein: 5, carbs: 65, fats: 22, fiber: 1.5, sugar: 30, serving_size: "4 pieces (50g)", health_warning: "High trans fat and sugar. Highly processed.", healthier_alternatives: "Oats biscuit or rice cakes.", exercises: [EX_CYCLE(480)], vitamins: [] },
  { food_name: "Energy Drink", food_category: "unhealthy", calories: 45, protein: 0, carbs: 11, fats: 0, fiber: 0, sugar: 11, serving_size: "1 can (250ml)", health_warning: "Very high caffeine and sugar. Can cause heart issues.", healthier_alternatives: "Green tea or coconut water.", exercises: [EX_WALK(112)], vitamins: [] },
  { food_name: "Fried Bhajiya / Pakoda", food_category: "unhealthy", calories: 280, protein: 5, carbs: 32, fats: 15, fiber: 3, sugar: 2, serving_size: "4 pieces (100g)", health_warning: "Deep fried. High fat content.", healthier_alternatives: "Baked vegetable fritters.", exercises: [EX_RUN(280)], vitamins: [] },
  { food_name: "Caramel Popcorn", food_category: "unhealthy", calories: 424, protein: 4, carbs: 78, fats: 11, fiber: 5, sugar: 45, serving_size: "1 cup (50g)", health_warning: "High in sugar and fat.", healthier_alternatives: "Plain air-popped popcorn.", exercises: [EX_CYCLE(424)], vitamins: [] },
  { food_name: "Cheese Sandwich (Grilled)", food_category: "moderate", calories: 300, protein: 11, carbs: 32, fats: 15, fiber: 1.5, sugar: 3, serving_size: "1 sandwich (150g)", health_warning: "High saturated fat from cheese and butter.", healthier_alternatives: "Multigrain bread with low-fat cheese.", exercises: [EX_CYCLE(300)], vitamins: [] },
  { food_name: "Pastry / Cake Slice", food_category: "unhealthy", calories: 400, protein: 5, carbs: 55, fats: 19, fiber: 0.5, sugar: 35, serving_size: "1 slice (100g)", health_warning: "Very high in sugar, refined flour and fat.", healthier_alternatives: "Homemade oat banana bread.", exercises: [EX_RUN(400)], vitamins: [] },
  { food_name: "Pani Puri (Fried)", food_category: "unhealthy", calories: 210, protein: 4, carbs: 32, fats: 8, fiber: 2, sugar: 2, serving_size: "6 pieces (120g)", health_warning: "Deep-fried shells, street food hygiene concerns.", healthier_alternatives: "Baked puri at home.", exercises: [EX_WALK(210)], vitamins: [] },

  // ─── HEALTHY FOODS ───
  { food_name: "Oats", food_category: "healthy", calories: 389, protein: 17, carbs: 66, fats: 7, fiber: 10, sugar: 0, serving_size: "1/2 cup dry (40g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Iron", amount: "4.7mg" }, { name: "Magnesium", amount: "177mg" }] },
  { food_name: "Brown Rice", food_category: "healthy", calories: 111, protein: 2.6, carbs: 23, fats: 0.9, fiber: 1.8, sugar: 0.4, serving_size: "1 cup cooked (195g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Magnesium", amount: "84mg" }, { name: "Phosphorus", amount: "150mg" }] },
  { food_name: "Quinoa", food_category: "healthy", calories: 120, protein: 4.4, carbs: 21, fats: 1.9, fiber: 2.8, sugar: 0.9, serving_size: "1 cup cooked (185g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Iron", amount: "2.8mg" }, { name: "Magnesium", amount: "118mg" }] },
  { food_name: "Greek Yogurt", food_category: "healthy", calories: 59, protein: 10, carbs: 3.6, fats: 0.4, fiber: 0, sugar: 3.2, serving_size: "1 cup (245g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Calcium", amount: "111mg" }, { name: "Vitamin B12", amount: "1.3mcg" }] },
  { food_name: "Almonds", food_category: "healthy", calories: 579, protein: 21, carbs: 22, fats: 50, fiber: 12.5, sugar: 4.4, serving_size: "30g (handful)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin E", amount: "25.6mg" }, { name: "Magnesium", amount: "270mg" }] },
  { food_name: "Walnuts", food_category: "healthy", calories: 654, protein: 15, carbs: 14, fats: 65, fiber: 6.7, sugar: 2.6, serving_size: "30g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Omega-3", amount: "2.5g" }, { name: "Magnesium", amount: "158mg" }] },
  { food_name: "Chia Seeds", food_category: "healthy", calories: 486, protein: 17, carbs: 42, fats: 31, fiber: 34, sugar: 0, serving_size: "2 tbsp (30g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Calcium", amount: "631mg" }, { name: "Iron", amount: "7.7mg" }] },
  { food_name: "Flaxseeds", food_category: "healthy", calories: 534, protein: 18, carbs: 29, fats: 42, fiber: 27, sugar: 1.5, serving_size: "1 tbsp (10g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Omega-3", amount: "2.3g" }, { name: "Magnesium", amount: "392mg" }] },
  { food_name: "Whole Egg", food_category: "healthy", calories: 155, protein: 13, carbs: 1.1, fats: 11, fiber: 0, sugar: 1.1, serving_size: "2 eggs (100g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin D", amount: "2mcg" }, { name: "Vitamin B12", amount: "1.1mcg" }] },
  { food_name: "Chicken Breast (Grilled)", food_category: "healthy", calories: 165, protein: 31, carbs: 0, fats: 3.6, fiber: 0, sugar: 0, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Niacin", amount: "14mg" }, { name: "Vitamin B6", amount: "1mg" }] },
  { food_name: "Salmon (Grilled)", food_category: "healthy", calories: 208, protein: 20, carbs: 0, fats: 13, fiber: 0, sugar: 0, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Omega-3", amount: "2.2g" }, { name: "Vitamin D", amount: "14.3mcg" }] },
  { food_name: "Tofu", food_category: "healthy", calories: 76, protein: 8, carbs: 1.9, fats: 4.8, fiber: 0.3, sugar: 0.5, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Calcium", amount: "350mg" }, { name: "Iron", amount: "5.4mg" }] },
  { food_name: "Lentils (Masoor Dal)", food_category: "healthy", calories: 116, protein: 9, carbs: 20, fats: 0.4, fiber: 7.9, sugar: 1.8, serving_size: "1 cup cooked (198g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Iron", amount: "3.3mg" }, { name: "Folate", amount: "358mcg" }] },
  { food_name: "Black Beans", food_category: "healthy", calories: 132, protein: 8.9, carbs: 24, fats: 0.5, fiber: 8.7, sugar: 0.3, serving_size: "1 cup cooked (172g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Iron", amount: "3.6mg" }, { name: "Magnesium", amount: "120mg" }] },
  { food_name: "Makhana (Fox Nuts)", food_category: "healthy", calories: 347, protein: 9.7, carbs: 76, fats: 0.1, fiber: 14.5, sugar: 0, serving_size: "30g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Magnesium", amount: "67mg" }, { name: "Calcium", amount: "60mg" }] },
  { food_name: "Green Tea", food_category: "healthy", calories: 2, protein: 0.2, carbs: 0.5, fats: 0, fiber: 0, sugar: 0, serving_size: "1 cup (240ml)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "EGCG", amount: "High" }, { name: "Antioxidants", amount: "Very High" }] },
  { food_name: "Coconut Water", food_category: "healthy", calories: 19, protein: 0.7, carbs: 3.7, fats: 0.2, fiber: 1.1, sugar: 2.6, serving_size: "1 cup (240ml)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Potassium", amount: "600mg" }, { name: "Magnesium", amount: "60mg" }] },
  { food_name: "Nimbu Pani (Lemonade)", food_category: "healthy", calories: 25, protein: 0.3, carbs: 6.7, fats: 0.1, fiber: 0.1, sugar: 5.8, serving_size: "1 glass (250ml)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "18mg" }] },
  { food_name: "Buttermilk (Chaas)", food_category: "healthy", calories: 40, protein: 3.3, carbs: 4.8, fats: 0.9, fiber: 0, sugar: 4.8, serving_size: "1 glass (250ml)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Calcium", amount: "115mg" }, { name: "Probiotics", amount: "High" }] },
  { food_name: "Protein Shake (Whey)", food_category: "healthy", calories: 120, protein: 25, carbs: 5, fats: 1.5, fiber: 0, sugar: 3, serving_size: "1 scoop in 300ml water", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Calcium", amount: "120mg" }] },
  { food_name: "Peanut Butter (Natural)", food_category: "healthy", calories: 588, protein: 25, carbs: 20, fats: 50, fiber: 6, sugar: 9, serving_size: "2 tbsp (32g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin E", amount: "9mg" }, { name: "Niacin", amount: "13.1mg" }] },
  { food_name: "Avocado", food_category: "healthy", calories: 160, protein: 2, carbs: 9, fats: 15, fiber: 7, sugar: 0.7, serving_size: "1/2 avocado (100g)", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin K", amount: "21mcg" }, { name: "Folate", amount: "81mcg" }] },
  { food_name: "Blueberries", food_category: "healthy", calories: 57, protein: 0.7, carbs: 14, fats: 0.3, fiber: 2.4, sugar: 10, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "9.7mg" }, { name: "Vitamin K", amount: "19.3mcg" }] },
  { food_name: "Sprouts (Mixed)", food_category: "healthy", calories: 30, protein: 3, carbs: 4, fats: 0.3, fiber: 1.5, sugar: 1, serving_size: "100g", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Vitamin C", amount: "13mg" }, { name: "Iron", amount: "1mg" }] },
  { food_name: "Sattu (Roasted Gram Flour)", food_category: "healthy", calories: 406, protein: 22, carbs: 65, fats: 6, fiber: 18, sugar: 3, serving_size: "30g mixed with water", health_warning: "", healthier_alternatives: "", exercises: [], vitamins: [{ name: "Iron", amount: "7.4mg" }, { name: "Calcium", amount: "163mg" }] },
];

// Build a lowercase search index once at startup — O(1) lookups thereafter
const _index = INDIAN_FOOD_LIBRARY.map((f, i) => ({
  i,
  words: f.food_name.toLowerCase().split(/[\s/()]+/).filter(Boolean),
  lower: f.food_name.toLowerCase(),
}));

/**
 * Fast match — returns best match or null.
 */
export function matchFood(foodName) {
  if (!foodName) return null;
  const query = foodName.toLowerCase().trim();

  // 1. Exact
  const exact = _index.find(e => e.lower === query);
  if (exact) return INDIAN_FOOD_LIBRARY[exact.i];

  // 2. Contains whole query string
  const contains = _index.find(e => e.lower.includes(query) || query.includes(e.lower));
  if (contains) return INDIAN_FOOD_LIBRARY[contains.i];

  // 3. Word scoring
  const queryWords = query.split(/[\s/()]+/).filter(w => w.length > 2);
  let bestIdx = -1, bestScore = 0;
  for (const { i, words } of _index) {
    let score = 0;
    for (const qw of queryWords) {
      if (words.some(w => w.includes(qw) || qw.includes(w))) score++;
    }
    if (score > bestScore) { bestScore = score; bestIdx = i; }
  }
  return bestScore > 0 ? INDIAN_FOOD_LIBRARY[bestIdx] : null;
}